# Generated by Django 5.2.9 on 2025-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPTRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('no_hp', models.CharField(blank=True, max_length=20, verbose_name='No. HP/WhatsApp')),
                ('paket_ppt', models.CharField(choices=[('basic', 'Paket Basic - Rp 50.000'), ('premium', 'Paket Premium - Rp 100.000'), ('enterprise', 'Paket Enterprise - Rp 200.000')], default='basic', max_length=50, verbose_name='Paket PPT')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Terkonfirmasi'), ('paid', 'Sudah Dibayar'), ('completed', 'Selesai')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Daftar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
            ],
            options={
                'verbose_name': 'Pendaftaran PPT',
                'verbose_name_plural': 'Pendaftaran PPT',
                'ordering': ['-created_at'],
            },
        ),
    ]
