# Generated by Django 5.2.9 on 2025-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pptregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token Verifikasi'),
        ),
    ]
