# Generated by Django 5.2.9 on 2025-12-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registrasi'), ('login', 'Login'), ('password_reset', 'Reset Password')], default='login', max_length=20, verbose_name='Tujuan'),
        ),
    ]
